services:
  - type: web
    name: f1driverlines
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn DriverComps:server
    disk:
      name: f1cache
      mountPath: /app/cache
